function execute() {
    return Response.success([
    //https://bato.to/browse?genres=comic&sort=views_m.za&page=3
    {title: "Comic", input:"https://bato.to/browse?genres=comic&sort=views_m.za&page=", script: "gen.js"},
    {title: "Manhwa", input:"https://bato.to/browse?genres=manhwa&sort=views_m.za&page=", script: "gen.js"},
    {title: "Manga", input:"https://bato.to/browse?genres=manga&sort=views_m.za&page=", script: "gen.js"},
    {title: "Manhua", input:"https://bato.to/browse?genres=manhua&sort=views_m.za&page=", script: "gen.js"},
    {title: "Webtoon", input:"https://bato.to/browse?genres=webtoon&sort=views_m.za&page=", script: "gen.js"},
    {title: "Josei", input:"https://bato.to/browse?genres=josei&sort=views_m.za&page=", script: "gen.js"},
    {title: "Seinen", input:"https://bato.to/browse?genres=seinen&sort=views_m.za&page=", script: "gen.js"},
    {title: "Shoujo", input:"https://bato.to/browse?genres=shoujo&sort=views_m.za&page=", script: "gen.js"},
    {title: "Shoujo Ai", input:"https://bato.to/browse?genres=shoujo_ai&sort=views_m.za&page=", script: "gen.js"},
    {title: "Shounen", input:"https://bato.to/browse?genres=shounen&sort=views_m.za&page=", script: "gen.js"},
    {title: "Shounen Ai", input:"https://bato.to/browse?genres=shounen_ai&sort=views_m.za&page=", script: "gen.js"},
    {title: "Yaoi", input:"https://bato.to/browse?genres=yaoi&sort=views_m.za&page=", script: "gen.js"},
    {title: "Yuri", input:"https://bato.to/browse?genres=yuri&sort=views_m.za&page=", script: "gen.js"},
    {title: "Ecchi", input:"https://bato.to/browse?genres=ecchi&sort=views_m.za&page=", script: "gen.js"},
    {title: "Mature", input:"https://bato.to/browse?genres=mature&sort=views_m.za&page=", script: "gen.js"},
    {title: "Adult", input:"https://bato.to/browse?genres=adult&sort=views_m.za&page=", script: "gen.js"},
    {title: "Gore", input:"https://bato.to/browse?genres=gore&sort=views_m.za&page=", script: "gen.js"},
    {title: "Violence", input:"https://bato.to/browse?genres=violence&sort=views_m.za&page=", script: "gen.js"},
    {title: "Smut", input:"https://bato.to/browse?genres=smut&sort=views_m.za&page=", script: "gen.js"},
    {title: "Hentai", input:"https://bato.to/browse?genres=hentai&sort=views_m.za&page=", script: "gen.js"},
    {title: "4-Koma", input:"https://bato.to/browse?genres=_4_koma&sort=views_m.za&page=", script: "gen.js"},
    {title: "Action", input:"https://bato.to/browse?genres=action&sort=views_m.za&page=", script: "gen.js"},
    {title: "Adaptation", input:"https://bato.to/browse?genres=adaptation&sort=views_m.za&page=", script: "gen.js"},
    {title: "Adventure", input:"https://bato.to/browse?genres=adventure&sort=views_m.za&page=", script: "gen.js"},
    {title: "Aliens", input:"https://bato.to/browse?genres=aliens&sort=views_m.za&page=", script: "gen.js"},
    {title: "Comedy", input:"https://bato.to/browse?genres=comedy&sort=views_m.za&page=", script: "gen.js"},
    {title: "Drama", input:"https://bato.to/browse?genres=drama&sort=views_m.za&page=", script: "gen.js"},
    {title: "Fantasy", input:"https://bato.to/browse?genres=fantasy&sort=views_m.za&page=", script: "gen.js"},
    {title: "Gender Bender", input:"https://bato.to/browse?genres=gender_bender&sort=views_m.za&page=", script: "gen.js"},
    {title: "Harem", input:"https://bato.to/browse?genres=harem&sort=views_m.za&page=", script: "gen.js"},
    {title: "Horror", input:"https://bato.to/browse?genres=horror&sort=views_m.za&page=", script: "gen.js"},
    {title: "Incest", input:"https://bato.to/browse?genres=incest&sort=views_m.za&page=", script: "gen.js"},
    {title: "Isekai", input:"https://bato.to/browse?genres=isekai&sort=views_m.za&page=", script: "gen.js"},
    {title: "Loli", input:"https://bato.to/browse?genres=loli&sort=views_m.za&page=", script: "gen.js"},
    {title: "Netorare/NTR", input:"https://bato.to/browse?genres=netorare&sort=views_m.za&page=", script: "gen.js"},
    {title: "Romance", input:"https://bato.to/browse?genres=romance&sort=views_m.za&page=", script: "gen.js"},
    {title: "School Life", input:"https://bato.to/browse?genres=school_life&sort=views_m.za&page=", script: "gen.js"},
    {title: "Sci-Fi", input:"https://bato.to/browse?genres=sci_fi&sort=views_m.za&page=", script: "gen.js"},
    {title: "Shota", input:"https://bato.to/browse?genres=shota&sort=views_m.za&page=", script: "gen.js"},
    {title: "Slice of Life", input:"https://bato.to/browse?genres=slice_of_life&sort=views_m.za&page=", script: "gen.js"},
    {title: "SM/BDSM", input:"https://bato.to/browse?genres=sm_bdsm&sort=views_m.za&page=", script: "gen.js"},

    ])
}