function execute() {
    return Response.success([

        {title: "Manga", input:"https://otakusan.net/Manga/MangaNewest", script: "gen.js"},
        {title: "Manhua", input:"https://otakusan.net/Manga/ManhuaNewest", script: "gen.js"},
        {title: "Manhwa", input:"https://otakusan.net/Manga/ManhwaNewest", script: "gen.js"},
        {title: "Light Novel", input:"https://otakusan.net/LightNovel/Newest", script: "gen.js"},
        //---------------------//
        {title: "4-Koma", input:"GenreDetail/41", script: "getgenre.js"},
        {title: "Action", input:"GenreDetail/26", script: "getgenre.js"},
        {title: "Adult", input:"GenreDetail/1", script: "getgenre.js"},
        {title: "Adventure", input:"GenreDetail/12", script: "getgenre.js"},
        {title: "Comedy", input:"GenreDetail/25", script: "getgenre.js"},
        {title: "Cooking", input:"GenreDetail/42", script: "getgenre.js"},
        {title: "Dark Fantansy", input:"GenreDetail/24", script: "getgenre.js"},
        {title: "Drama", input:"GenreDetail/13", script: "getgenre.js"},
        {title: "Ecchi", input:"GenreDetail/14", script: "getgenre.js"},
        {title: "Fantasy", input:"GenreDetail/2", script: "getgenre.js"},
        {title: "Gender Bender", input:"GenreDetail/37", script: "getgenre.js"},
        {title: "Harem", input:"GenreDetail/15", script: "getgenre.js"},
        {title: "Historical", input:"GenreDetail/36", script: "getgenre.js"},
        {title: "Horror", input:"GenreDetail/16", script: "getgenre.js"},
        {title: "Isekai FTensei", input:"GenreDetail/40", script: "getgenre.js"},
        {title: "Josei", input:"GenreDetail/39", script: "getgenre.js"},
        {title: "Magic", input:"GenreDetail/3", script: "getgenre.js"},
        {title: "Martial Art", input:"GenreDetail/38", script: "getgenre.js"},
        {title: "Mature", input:"GenreDetail/48", script: "getgenre.js"},
        {title: "Mecha", input:"GenreDetail/9", script: "getgenre.js"},
        {title: "Music", input:"GenreDetail/46", script: "getgenre.js"},
        {title: "Mystery", input:"GenreDetail/4", script: "getgenre.js"},
        {title: "Office workers", input:"GenreDetail/49", script: "getgenre.js"},
        {title: "One shot", input:"GenreDetail/17", script: "getgenre.js"},
        {title: "Psychological", input:"GenreDetail/18", script: "getgenre.js"},
        {title: "Reverse harem", input:"GenreDetail/47", script: "getgenre.js"},
        {title: "Romance", input:"GenreDetail/28", script: "getgenre.js"},
        {title: "Sci-Fi Sci", input:"GenreDetail/10", script: "getgenre.js"},
        {title: "School Life", input:"GenreDetail/11", script: "getgenre.js"},
        {title: "Seinen", input:"GenreDetail/5", script: "getgenre.js"},
        {title: "Shoujo", input:"GenreDetail/34", script: "getgenre.js"},
        {title: "Shoujo Ai", input:"GenreDetail/33", script: "getgenre.js"},
        {title: "Shounen", input:"GenreDetail/29", script: "getgenre.js"},
        {title: "Shounen Ai", input:"GenreDetail/43", script: "getgenre.js"},
        {title: "Slice of life", input:"GenreDetail/35", script: "getgenre.js"},
        {title: "Smut", input:"GenreDetail/6", script: "getgenre.js"},
        {title: "Sports", input:"GenreDetail/19", script: "getgenre.js"},
        {title: "Super Natural", input:"GenreDetail/30", script: "getgenre.js"},
        {title: "Tragedy", input:"GenreDetail/20", script: "getgenre.js"},
        {title: "Trap/Cross-dressing", input:"GenreDetail/44", script: "getgenre.js"},
        {title: "VnComic", input:"GenreDetail/45", script: "getgenre.js"},
        {title: "Webtoon", input:"GenreDetail/31", script: "getgenre.js"},
        {title: "Yaoi", input:"GenreDetail/27", script: "getgenre.js"},
        {title: "Yuri", input:"GenreDetail/32", script: "getgenre.js"}
    ]);
}